<a href="https://colab.research.google.com/github/0110225117-max/Selamat-Ultah-Ummiiiii/blob/main/P02_Praktikum_Pandas_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Praktikum Pertemuan 2 — pandas di Google Colab
**Mata Kuliah:** Exploratory Data Analysis (KMTI21133) — Pertemuan 2
**Sub-CPMK2:** Mahasiswa mampu menggunakan Python (pandas) di Google Colab/Jupyter dan Git/GitHub untuk memuat, menelusuri, dan menyimpan data serta kode analisis.

**Cara kerja:** sel bertanda `# DEMO` diisi bersama dosen; sel bertanda `# TODO` Anda kerjakan sendiri. Setiap TODO punya *expected output* agar Anda bisa memeriksa jawaban sendiri. Simpan notebook ini ke repositori tim di akhir sesi (Bagian E).

## Bagian 0 — Persiapan
Jalankan sel di bawah. Jika file `penjualan_umkm_2024.csv` belum ada di sesi Colab, sel akan meminta Anda mengunggahnya (ikon folder di kiri → Upload).

In [2]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 30)
pd.set_option('display.width', 120)
print('pandas', pd.__version__, '| numpy', np.__version__)

pandas 2.2.3 | numpy 2.1.3

In [4]:
import os
FILE = 'penjualan_umkm_2024.csv'

if not os.path.exists(FILE):
    try:
        from google.colab import files
        files.upload()          # pilih penjualan_umkm_2024.csv
    except ImportError:
        raise FileNotFoundError('Letakkan CSV di folder yang sama dengan notebook ini.')
print('Siap:', os.path.exists(FILE))

Siap: True

---
## Bagian A — Memuat dan memeriksa data (Latihan 1)
**Tujuan:** sebelum menganalisis apa pun, jawab empat pertanyaan: *berapa besar data ini, apa saja kolomnya, apa tipe datanya, dan seberapa bersih?*

In [5]:
# DEMO A1 — memuat data
df = pd.read_csv('penjualan_umkm_2024.csv')
df.head()

,id_transaksi,tanggal,kota,kategori,produk,jumlah,harga_satuan,diskon_persen,metode_bayar,rating_pelanggan,total_bayar
0,TRX2024198,2024-11-14,Jakarta Selatan,Makanan,Sambal Roa,8,38000,5,Transfer,4.7,288800
1,TRX2025061,2024-08-16,Depok,Fashion,Kaos Lokal,8,131500,15,Tunai,3.8,894200
2,TRX2024249,2024-12-21,Depok,Fashion,Hijab Motif,12,102500,10,E-Wallet,4.3,1107000
3,TRX2024903,2024-09-27,Bekasi,Fashion,Kemeja Tenun,11,113500,10,E-Wallet,NaN,1123650
4,TRX2024097,2024-05-06,Depok,Kerajinan,Batik Tulis,8,123000,20,QRIS,4.5,787200

In [6]:
# DEMO A2 — ukuran dan struktur
print('Baris, kolom:', df.shape)
df.info()

Baris, kolom: (1212, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1212 entries, 0 to 1211
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_transaksi      1212 non-null   object
 1   tanggal           1212 non-null   object
 2   kota              1212 non-null   object
 3   kategori          1212 non-null   object
 4   produk            1212 non-null   object
 5   jumlah            1212 non-null   int64
 6   harga_satuan      1212 non-null   int64
 7   diskon_persen     1212 non-null   int64
 8   metode_bayar      1187 non-null   object
 9   rating_pelanggan  1151 non-null   float64
 10  total_bayar       1212 non-null   int64
dtypes: float64(1), int64(4), object(6)
memory usage: 104.3+ KB

In [11]:
# DEMO A3 — ringkasan numerik
df.describe()

            jumlah   harga_satuan  diskon_persen  rating_pelanggan   total_bayar
count  1212.000000    1212.000000    1212.000000       1151.000000  1.212000e+03
mean      7.548680   69210.808581       6.839934          4.152389  4.859965e+05
std       4.055776   50222.966019       7.446309          0.541938  4.826499e+05
min       1.000000   20000.000000       0.000000          2.500000  1.760000e+04
25%       4.000000   30500.000000       0.000000          3.800000  1.655000e+05
50%       8.000000   39500.000000       5.000000          4.200000  3.049750e+05
75%      11.000000  113000.000000      15.000000          4.600000  6.239625e+05
max      14.000000  191500.000000      20.000000          5.000000  2.667000e+06

> **Catatan dosen:** `describe()` secara default hanya meringkas kolom numerik. Coba `df.describe(include='object')` untuk kolom teks.

In [12]:
# TODO A4
# a. Tampilkan 5 baris TERAKHIR dari df
# b. Tampilkan daftar nama kolom beserta tipe datanya
# Expected: 1212 baris x 11 kolom; kolom 'tanggal' bertipe object (belum datetime)

print('5 baris terakhir:')
df.tail()

5 baris terakhir:

,id_transaksi,tanggal,kota,kategori,produk,jumlah,harga_satuan,diskon_persen,metode_bayar,rating_pelanggan,total_bayar
1207,TRX2025021,2024-11-18,Tangerang Selatan,Makanan,Keripik Singkong,1,22000,20,QRIS,4.1,17600
1208,TRX2024789,2024-09-16,Bogor,Minuman,Teh Herbal,5,55000,10,Transfer,NaN,247500
1209,TRX2024256,2024-08-13,Bogor,Minuman,Sirup Markisa,2,47000,10,QRIS,3.6,84600
1210,TRX2024968,2024-01-08,Bekasi,Kerajinan,Tas Anyaman,7,132000,20,Transfer,4.6,739200
1211,TRX2024952,2024-03-11,Bekasi,Minuman,Teh Herbal,7,29500,20,Transfer,4.4,165200

In [14]:
# TODO A5 — seberapa bersih data ini?
# a. Hitung jumlah nilai kosong (missing) per kolom
# b. Hitung jumlah baris duplikat
# c. Hitung berapa nilai unik pada kolom 'kota'
# Expected: rating_pelanggan & metode_bayar memiliki missing; ada 12 baris duplikat;
#           kolom 'kota' punya LEBIH dari 5 nilai unik -- mengapa? (diskusikan)
print('\nDaftar kolom dan tipe datanya:')
df.info()
print("Jumlah missing value per kolom:")
print(df.isna().sum())
print("\nJumlah baris duplikat:")
print(df.duplicated().sum())
print("\nJumlah nilai unik pada kolom 'kota':")
print(df['kota'].nunique())

Daftar kolom dan tipe datanya:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1212 entries, 0 to 1211
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_transaksi      1212 non-null   object
 1   tanggal           1212 non-null   object
 2   kota              1212 non-null   object
 3   kategori          1212 non-null   object
 4   produk            1212 non-null   object
 5   jumlah            1212 non-null   int64
 6   harga_satuan      1212 non-null   int64
 7   diskon_persen     1212 non-null   int64
 8   metode_bayar      1187 non-null   object
 9   rating_pelanggan  1151 non-null   float64
 10  total_bayar       1212 non-null   int64
dtypes: float64(1), int64(4), object(6)
memory usage: 104.3+ KB
Jumlah missing value per kolom:
id_transaksi         0
tanggal              0
kota                 0
kategori             0
produk               0
jumlah               0
harga_satuan         0
diskon_persen        0
metode_bayar        25
rating_pelanggan    61
total_bayar          0
dtype: int64

Jumlah baris duplikat:
12

Jumlah nilai unik pada kolom 'kota':
10

**Diskusi (2 menit):** mengapa jumlah nilai unik `kota` lebih banyak daripada jumlah kota sebenarnya? Masalah seperti ini akan kita tangani secara sistematis pada pertemuan 4–5.

---
## Bagian B — Seleksi dan filter (Latihan 2, berpasangan)
**Tujuan:** mengambil bagian data yang relevan dengan pertanyaan analisis.

In [15]:
# DEMO B1 — memilih kolom
df['total_bayar'].head()          # satu kolom -> Series
df[['kota','kategori','total_bayar']].head()   # beberapa kolom -> DataFrame

              kota   kategori  total_bayar
0  Jakarta Selatan    Makanan       288800
1            Depok    Fashion       894200
2            Depok    Fashion      1107000
3           Bekasi    Fashion      1123650
4            Depok  Kerajinan       787200

In [16]:
# DEMO B2 — loc (berbasis label) vs iloc (berbasis posisi)
print(df.loc[0, 'produk'])
print(df.iloc[0, 4])
df.loc[0:4, ['produk','jumlah','total_bayar']]

Sambal Roa
Sambal Roa

         produk  jumlah  total_bayar
0    Sambal Roa       8       288800
1    Kaos Lokal       8       894200
2   Hijab Motif      12      1107000
3  Kemeja Tenun      11      1123650
4   Batik Tulis       8       787200

In [17]:
# DEMO B3 — filter dengan kondisi (boolean mask)
mask = df['total_bayar'] > 1_000_000
print('Transaksi di atas 1 juta:', mask.sum())
df[mask].head()

Transaksi di atas 1 juta: 180

,id_transaksi,tanggal,kota,kategori,produk,jumlah,harga_satuan,diskon_persen,metode_bayar,rating_pelanggan,total_bayar
2,TRX2024249,2024-12-21,Depok,Fashion,Hijab Motif,12,102500,10,E-Wallet,4.3,1107000
3,TRX2024903,2024-09-27,Bekasi,Fashion,Kemeja Tenun,11,113500,10,E-Wallet,NaN,1123650
36,TRX2024121,2024-05-31,Bekasi,Kerajinan,Batik Tulis,13,132000,5,Tunai,4.4,1630200
39,TRX2024692,2024-08-07,Depok,Kerajinan,Gerabah Hias,10,107000,0,Transfer,4.4,1070000
42,TRX2024232,2024-08-26,Tangerang Selatan,Kerajinan,Tas Anyaman,14,135500,0,QRIS,3.6,1897000

In [18]:
# DEMO B4 — menggabungkan kondisi
hi = df[(df['kategori'] == 'Makanan') & (df['diskon_persen'] >= 10)]
print(hi.shape)
df[df['metode_bayar'].isin(['QRIS','E-Wallet'])].shape

(201, 11)

(648, 11)

In [33]:
# TODO B5
# a. Ambil semua transaksi dengan rating_pelanggan < 3
rating_rendah = df[df['rating_pelanggan'] < 3]

# b. Berapa banyak transaksi tersebut dan berapa rata-rata total_bayar-nya?
banyak_transaksi = len(rating_rendah)
rata_total_bayar = rating_rendah['total_bayar'].mean()

print(f"Banyak transaksi (rating < 3): {banyak_transaksi}")
print(f"Rata-rata total_bayar: {rata_total_bayar:.2f}")

# c. Ambil transaksi kategori 'Kerajinan' ATAU 'Fashion' dengan jumlah >= 10
transaksi_c = df[(df['kategori'].isin(['Kerajinan', 'Fashion'])) & (df['jumlah'] >= 10)]
print("\nTransaksi Kerajinan/Fashion dengan jumlah >= 10:")
print(transaksi_c)
df_filtered
df_filtered

Banyak transaksi (rating < 3): 19
Rata-rata total_bayar: 386563.16

Transaksi Kerajinan/Fashion dengan jumlah >= 10:
     id_transaksi     tanggal               kota   kategori        produk  jumlah  harga_satuan  diskon_persen  \
2      TRX2024249  2024-12-21              Depok    Fashion   Hijab Motif      12        102500             10
3      TRX2024903  2024-09-27             Bekasi    Fashion  Kemeja Tenun      11        113500             10
36     TRX2024121  2024-05-31             Bekasi  Kerajinan   Batik Tulis      13        132000              5
39     TRX2024692  2024-08-07              Depok  Kerajinan  Gerabah Hias      10        107000              0
42     TRX2024232  2024-08-26  Tangerang Selatan  Kerajinan   Tas Anyaman      14        135500              0
...           ...         ...                ...        ...           ...     ...           ...            ...
1132   TRX2024076  2024-03-14  Tangerang Selatan  Kerajinan  Gerabah Hias      14        149000             15
1138   TRX2024503  2024-09-17              Depok  Kerajinan   Tas Anyaman      12        117500             10
1152   TRX2024036  2024-11-18              Bogor  Kerajinan  Gerabah Hias      12        106000              0
1177   TRX2024704  2024-07-31             Bekasi  Kerajinan  Gerabah Hias      10        162000              0
1199   TRX2024398  2024-08-10              Bogor  Kerajinan   Batik Tulis      14        143000              0

     metode_bayar  rating_pelanggan  total_bayar kelas_nilai     hemat
2        E-Wallet               4.3      1107000       Besar  123000.0
3        E-Wallet               NaN      1123650       Besar  124850.0
36          Tunai               4.4      1630200       Besar   85800.0
39       Transfer               4.4      1070000       Besar       0.0
42           QRIS               3.6      1897000       Besar       0.0
...           ...               ...          ...         ...       ...
1132         QRIS               5.0      1773100       Besar  312900.0
1138         QRIS               4.1      1269000       Besar  141000.0
1152         QRIS               5.0      1272000       Besar       0.0
1177         QRIS               3.5      1620000       Besar       0.0
1199         QRIS               3.1      2002000       Besar       0.0

[164 rows x 13 columns]

,id_transaksi,tanggal,kota,kategori,produk,jumlah,harga_satuan,diskon_persen,metode_bayar,rating_pelanggan,total_bayar,kelas_nilai,hemat
2,TRX2024249,2024-12-21,Depok,Fashion,Hijab Motif,12,102500,10,E-Wallet,4.3,1107000,Besar,123000.0
3,TRX2024903,2024-09-27,Bekasi,Fashion,Kemeja Tenun,11,113500,10,E-Wallet,NaN,1123650,Besar,124850.0
36,TRX2024121,2024-05-31,Bekasi,Kerajinan,Batik Tulis,13,132000,5,Tunai,4.4,1630200,Besar,85800.0
39,TRX2024692,2024-08-07,Depok,Kerajinan,Gerabah Hias,10,107000,0,Transfer,4.4,1070000,Besar,0.0
42,TRX2024232,2024-08-26,Tangerang Selatan,Kerajinan,Tas Anyaman,14,135500,0,QRIS,3.6,1897000,Besar,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1132,TRX2024076,2024-03-14,Tangerang Selatan,Kerajinan,Gerabah Hias,14,149000,15,QRIS,5.0,1773100,Besar,312900.0
1138,TRX2024503,2024-09-17,Depok,Kerajinan,Tas Anyaman,12,117500,10,QRIS,4.1,1269000,Besar,141000.0
1152,TRX2024036,2024-11-18,Bogor,Kerajinan,Gerabah Hias,12,106000,0,QRIS,5.0,1272000,Besar,0.0
1177,TRX2024704,2024-07-31,Bekasi,Kerajinan,Gerabah Hias,10,162000,0,QRIS,3.5,1620000,Besar,0.0
1199,TRX2024398,2024-08-10,Bogor,Kerajinan,Batik Tulis,14,143000,0,QRIS,3.1,2002000,Besar,0.0

In [39]:
# TODO B6 — pertanyaan bisnis
# 'Transaksi tunai bernilai besar (> 500.000) di kota mana saja?'
# Tampilkan kolom kota, produk, jumlah, total_bayar, diurutkan dari total_bayar terbesar.
# Petunjuk: gunakan .sort_values(..., ascending=False) dan .head(10)
# Filter transaksi tunai (> 500.000)
df_tunai_besar = df[(df['metode_bayar'] == 'Tunai') & (df['total_bayar'] > 500000)]

# Tampilkan kolom spesifik, diurutkan dari total_bayar terbesar (10 teratas)
hasil = df_tunai_besar[['kota', 'produk', 'jumlah', 'total_bayar']].sort_values(by='total_bayar', ascending=False).head(10)

hasil

                 kota        produk  jumlah  total_bayar
385            Bekasi   Batik Tulis      14      2667000
97             Bekasi  Gerabah Hias      12      2286000
742   Jakarta Selatan   Batik Tulis      13      2242500
988             Bogor   Batik Tulis      14      2237200
398   Jakarta Selatan  Kemeja Tenun      14      2093000
129             Bogor   Batik Tulis      13      2054000
116            Bekasi  Gerabah Hias      14      1999200
252             Depok   Hijab Motif      14      1988000
168             Bogor  Gerabah Hias      13      1982500
1000  Jakarta Selatan  Gerabah Hias      11      1947000

---
## Bagian C — Kolom turunan dan pengurutan

In [40]:
# DEMO C1 — membuat kolom baru
df['harga_bruto'] = df['jumlah'] * df['harga_satuan']
df['hemat'] = df['harga_bruto'] - df['total_bayar']
df[['harga_bruto','total_bayar','hemat']].head()

   harga_bruto  total_bayar   hemat
0       304000       288800   15200
1      1052000       894200  157800
2      1230000      1107000  123000
3      1248500      1123650  124850
4       984000       787200  196800

In [41]:
# DEMO C2 — kolom tanggal
df['tanggal'] = pd.to_datetime(df['tanggal'])
df['bulan'] = df['tanggal'].dt.month
df['nama_hari'] = df['tanggal'].dt.day_name()
df[['tanggal','bulan','nama_hari']].head()

     tanggal  bulan nama_hari
0 2024-11-14     11  Thursday
1 2024-08-16      8    Friday
2 2024-12-21     12  Saturday
3 2024-09-27      9    Friday
4 2024-05-06      5    Monday

In [42]:
# TODO C3

import numpy as np

# a. Buat kolom 'kelas_nilai'
df['kelas_nilai'] = np.where(df['total_bayar'] > 500000, 'Besar', 'Kecil')

# b. Hitung jumlah transaksi per kelas nilai
df['kelas_nilai'].value_counts()

# c. Hitung penghematan (kolom 'hemat') dan tampilkan 5 transaksi terbesar
df['hemat'] = df['jumlah'] * df['harga_satuan'] * (df['diskon_persen'] / 100)
df.sort_values(by='hemat', ascending=False).head(5)

,id_transaksi,tanggal,kota,kategori,produk,jumlah,harga_satuan,diskon_persen,metode_bayar,rating_pelanggan,total_bayar,kelas_nilai,hemat,harga_bruto,bulan,nama_hari
295,TRX2024224,2024-02-13,Jakarta Selatan,Kerajinan,Gerabah Hias,14,179500,20,Transfer,4.1,2010400,Besar,502600.0,2513000,2,Tuesday
155,TRX2024618,2024-06-15,Jakarta Selatan,Kerajinan,Batik Tulis,14,169500,20,E-Wallet,3.8,1898400,Besar,474600.0,2373000,6,Saturday
220,TRX2024902,2024-02-04,Jakarta Selatan,Kerajinan,Batik Tulis,13,182500,20,QRIS,4.1,1898000,Besar,474500.0,2372500,2,Sunday
112,TRX2025135,2024-07-05,Tangerang Selatan,Kerajinan,Gerabah Hias,13,176500,20,Transfer,4.0,1835600,Besar,458900.0,2294500,7,Friday
381,TRX2025146,2024-10-08,Bogor,Kerajinan,Gerabah Hias,13,163000,20,Transfer,NaN,1695200,Besar,423800.0,2119000,10,Tuesday

---
## Bagian D — Agregasi dengan groupby
Pola yang akan Anda pakai sepanjang semester: **split → apply → combine**.

In [ ]:
# DEMO D1 — agregasi sederhana
df.groupby('kategori')['total_bayar'].mean().round(0)

In [ ]:
# DEMO D2 — beberapa agregasi sekaligus
ringkas = (df.groupby('kategori')
             .agg(jumlah_transaksi=('id_transaksi','count'),
                  total_penjualan=('total_bayar','sum'),
                  rata_rata_nilai=('total_bayar','mean'),
                  rata_rata_rating=('rating_pelanggan','mean'))
             .round(2)
             .sort_values('total_penjualan', ascending=False))
ringkas

In [ ]:
# DEMO D3 — dua kunci pengelompokan
df.groupby(['kategori','metode_bayar'])['total_bayar'].sum().unstack(fill_value=0)

In [43]:
# TODO D4
# a. Total penjualan per kota (dibersihkan kapitalisasinya)
df['kota_clean'] = df['kota'].str.strip().str.title()
penjualan_kota = (
    df.groupby('kota_clean')['total_bayar'].sum().sort_values(ascending=False)
)
print(penjualan_kota)

# b. Rata-rata rating per kategori
rating_kategori = df.groupby('kategori')['rating_pelanggan'].mean().sort_values()
print(rating_kategori)

# c. Penjualan per bulan
df['tanggal'] = pd.to_datetime(df['tanggal'])
df['bulan'] = df['tanggal'].dt.to_period('M')
penjualan_bulan = (
    df.groupby('bulan')['total_bayar'].sum().sort_values(ascending=False)
)
print(penjualan_bulan)

kota_clean
Depok                176682200
Jakarta Selatan      138703975
Bogor                107007325
Bekasi                99748225
Tangerang Selatan     66886000
Name: total_bayar, dtype: int64
kategori
Fashion      4.122162
Minuman      4.125455
Kerajinan    4.142553
Makanan      4.185965
Name: rating_pelanggan, dtype: float64
bulan
2024-02    66337075
2024-08    61894850
2024-10    56717775
2024-05    54628625
2024-09    47897550
2024-01    46993050
2024-03    45833275
2024-11    45640975
2024-04    45592425
2024-07    42360050
2024-12    38019650
2024-06    37112425
Freq: M, Name: total_bayar, dtype: int64

In [44]:
# TODO D5 — satu temuan
# Tulis SATU kalimat temuan dari hasil di atas dalam sel Markdown berikutnya.
# Format: 'X memiliki ... sebesar ..., lebih tinggi/rendah dibandingkan ...'
# Ingat: ini temuan DESKRIPTIF, belum boleh diklaim sebagai sebab-akibat.

SyntaxError: invalid syntax (2163339818.py, line 7)

**Temuan saya:** _(tulis di sini)_

---
## Bagian E — Menyimpan hasil dan mengunggah ke repositori tim

In [ ]:
# DEMO E1 — menyimpan hasil agregasi
ringkas.to_csv('ringkasan_kategori.csv')
print('Tersimpan.')
# Di Colab: files.download('ringkasan_kategori.csv') untuk mengunduh

### Alur kerja repositori tim (dilakukan bersama di kelas)
```
nama-tim-eda/
├── README.md              <- tujuan proyek, anggota, cara menjalankan
├── requirements.txt
├── data/
│   ├── raw/               <- data asli, TIDAK PERNAH diubah
│   └── processed/         <- hasil olahan
├── notebooks/             <- 01_quality.ipynb, 02_cleaning.ipynb, ...
├── knime/
└── reports/
```
**Dua cara menyimpan notebook ke GitHub:**
1. Colab → *File → Save a copy in GitHub* → pilih repo tim → tulis pesan commit.
2. Melalui terminal/Git lokal:
```bash
git clone https://github.com/<organisasi-tim>/<nama-repo>.git
cd <nama-repo>
git checkout -b latihan-pert2
git add notebooks/P02_praktikum.ipynb
git commit -m 'Latihan pert 2: eksplorasi awal data penjualan UMKM'
git push origin latihan-pert2
```
**Aturan pesan commit di kelas ini:** kalimat perintah, maksimal ±60 karakter, menjelaskan *apa* dan *mengapa*.
Contoh baik: `Tambah agregasi penjualan per kota`. Contoh buruk: `update`, `fix`, `asdf`.

In [ ]:
# TODO E2 — checklist sebelum commit
# 1. Restart runtime lalu Run all -> pastikan tidak ada error
# 2. Hapus sel percobaan yang tidak terpakai
# 3. Pastikan nama file mengikuti pola: P02_praktikum_<nama>.ipynb
# 4. Commit & push, lalu salin tautan commit Anda ke LMS

---
## Bagian F — Checkpoint proyek (dikerjakan bersama tim, di luar kelas)
Terapkan Bagian A pada **dataset calon proyek tim Anda**, lalu jawab di README repositori:
1. Berapa baris dan kolom? Apa satuan tiap barisnya (satu baris = satu apa)?
2. Kolom mana yang numerik, kategorikal, dan tanggal?
3. Kolom mana yang bermasalah (kosong, tipe salah, nilai tidak konsisten)?
4. Apakah data ini cukup untuk menjawab pertanyaan analisis tim? Jika belum, apa yang kurang?

Hasil poin 1–4 menjadi bahan **M1 (proposal proyek)** yang dikumpulkan pada pertemuan 3.